/* config.h.  Generated by cmake from config.h.cmake */

/* Define if messsage translations are enabled */
#cmakedefine ENABLE_NLS 1

/* */
#undef HAVE_GETTEXT

/* Define to 1 if you have the <inttypes.h> header file. */
#cmakedefine HAVE_INTTYPES_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Define to 1 if you have the <libgen.h> header file. */
#cmakedefine HAVE_LIBGEN_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define to 1 if you have the <direct.h> header file. */
#cmakedefine HAVE_DIRECT_H 1

/* Define to 1 if you have the <strings.h> header file. */
#cmakedefine HAVE_STRINGS_H 1

/* Define to 1 if you have the <sys/cdefs.h> header file. */
#cmakedefine HAVE_SYS_CDEFS_H 1

/* Define to 1 if you have the `abort' function. */
#cmakedefine HAVE_ABORT 1

/* Define to 1 if you have the `toascii' function. */
#cmakedefine HAVE_TOASCII 1

/* Define to 1 if you have the `vsnprintf' function. */
#cmakedefine HAVE_VSNPRINTF 1

/* Define to 1 if you have the `getcwd' function. */
#cmakedefine HAVE_GETCWD 1

/* Define to 1 if you have the `strcasecmp' function. */
#cmakedefine HAVE_STRCASECMP 1

/* Define to 1 if you have the `strncasecmp' function. */
#cmakedefine HAVE_STRNCASECMP 1

/* Define to 1 if you have the `stricmp' function. */
#cmakedefine HAVE_STRICMP 1

/* Define to 1 if you have the `strcmpi' function. */
#cmakedefine HAVE_STRCMPI 1

/* Define to 1 if you have the `_stricmp' function. */
#cmakedefine HAVE__STRICMP 1

/* Define to 1 if you have the `_strcmpi' function. */
#cmakedefine HAVE__STRCMPI 1

/* Name of package */
#define PACKAGE "yasm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bug-yasm@tortall.net"

/* Define to internal version of this package. */
#cmakedefine PACKAGE_INTVER

/* Define to the full name of this package. */
#define PACKAGE_NAME "yasm"

/* Define to the full name and version of this package. */
#cmakedefine PACKAGE_STRING

/* Define to the version of this package. */
#cmakedefine PACKAGE_VERSION
