# Path to the cxxtestgen.py script
SET(CXXTESTGEN ${yasm_SOURCE_DIR}/cxxtest/cxxtestgen.py)

MACRO(ADD_CXXTEST NAME)
  INCLUDE_DIRECTORIES(${yasm_SOURCE_DIR}/cxxtest)
  INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})

  IF(PYTHONINTERP_FOUND)
    ADD_CUSTOM_COMMAND(
      OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NAME}.cpp
      COMMAND
        ${PYTHON_EXECUTABLE} ${CXXTESTGEN}
        --runner=ErrorPrinter
        -o ${CMAKE_CURRENT_BINARY_DIR}/${NAME}.cpp ${ARGN}
      DEPENDS ${ARGN}
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    )
  ENDIF(PYTHONINTERP_FOUND)

  YASM_ADD_UNIT_TEST(${NAME} ${CMAKE_CURRENT_BINARY_DIR}/${NAME})
ENDMACRO(ADD_CXXTEST)

