# Path to the cxxtestgen.py script
SET(CXXTESTGEN ${yasm_SOURCE_DIR}/cxxtest/cxxtestgen.py)

MACRO(ADD_CXXTEST NAME)
  INCLUDE_DIRECTORIES(${yasm_SOURCE_DIR}/cxxtest)
  INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})

  SET(_CXXTEST_ARGS)
  SET(_EXTRA_SRCS)
  SET(_IS_EXTRA FALSE)
  FOREACH(_arg ${ARGN})
    IF(_arg STREQUAL "EXTRA_SRCS")
      SET(_IS_EXTRA TRUE)
    ELSE(_arg STREQUAL "EXTRA_SRCS")
      IF(_IS_EXTRA)
        LIST(APPEND _EXTRA_SRCS ${_arg})
      ELSE(_IS_EXTRA)
        LIST(APPEND _CXXTEST_ARGS ${_arg})
      ENDIF(_IS_EXTRA)
    ENDIF(_arg STREQUAL "EXTRA_SRCS")
  ENDFOREACH(_arg)

  SET(_RUNNER ErrorPrinter)
  IF(MSVC)
    SET(_RUNNER ParenPrinter)
  ENDIF(MSVC)

  IF(PYTHONINTERP_FOUND)
    ADD_CUSTOM_COMMAND(
      OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NAME}.cpp
      COMMAND
        ${PYTHON_EXECUTABLE} ${CXXTESTGEN}
        --runner=${_RUNNER}
        --have-eh
        --have-std
        -o ${CMAKE_CURRENT_BINARY_DIR}/${NAME}.cpp ${ARGN}
      DEPENDS ${_CXXTEST_ARGS}
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    )
  ENDIF(PYTHONINTERP_FOUND)

  YASM_ADD_UNIT_TEST(${NAME} ${CMAKE_CURRENT_BINARY_DIR}/${NAME} ${_EXTRA_SRCS})
ENDMACRO(ADD_CXXTEST)

