# $Id: Makefile 2301 2010-03-09 23:59:23Z peter $
DOC=	manual
MASTERDOC=	manual.txt

SRCS= manual-docinfo.xml
SRCS+= introduction.txt
SRCS+= running.txt
SRCS+= vsyasm.txt
SRCS+= nasm-language.txt
SRCS+= nasm-preprocessor.txt
SRCS+= nasm-directives.txt
SRCS+= objfmt-bin.txt
SRCS+= objfmt-coff.txt
SRCS+= objfmt-elf32.txt
SRCS+= objfmt-elf64.txt
SRCS+= objfmt-macho32.txt
SRCS+= objfmt-macho64.txt
SRCS+= objfmt-rdf.txt
SRCS+= objfmt-win32.txt
SRCS+= objfmt-win64.txt
SRCS+= objfmt-xdf.txt
SRCS+= dbgfmt-cv8.txt
SRCS+= dbgfmt-dwarf2.txt
SRCS+= dbgfmt-stabs.txt
SRCS+= arch-x86.txt

IMAGES=  objfmt-win64/calling-convention.pic
IMAGES+= objfmt-win64/stack-frame-detailed.pic
IMAGES+= arch-x86/x86-registers.pic

include ../share/mk/doc.asciidoc.mk
